### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-okta

on: [push]

jobs:
  tox:

    runs-on: ubuntu-latest
    env:
      TAP_OKTA_API_KEY: ${{secrets.TAP_OKTA_API_KEY}}
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Run all tox suite - pytest & linters[black,flake8,pydocstyle,mypy]
      run: |
        poetry add tox
        poetry run tox

